#!/bin/sh
featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2016.R1.txt 2016/R1/Aligned.out.bam 
featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2016.R2.txt 2016/R2/Aligned.out.bam

featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2018.exp1.R1.txt 2018/exp1/R1/Aligned.out.bam 
featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2016.exp1.R2.txt 2018/exp1/R2/Aligned.out.bam
featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2018.exp1.I1.txt 2018/exp1/I1/Aligned.out.bam

featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2018.exp2.R1.txt 2018/exp2/R1/Aligned.out.bam 
featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2016.exp2.R2.txt 2018/exp2/R2/Aligned.out.bam
featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2018.exp2.I1.txt 2018/exp2/I1/Aligned.out.bam 

featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2018.exp3.R1.txt 2018/exp3/R1/Aligned.out.bam 
featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2016.exp3.R2.txt 2018/exp3/R2/Aligned.out.bam
featureCounts -p -T 5 -g gene_id -F GTF -a Danio_rerio.GRCz11.94.abinitio.v2.gtf -o featurecounts/featurecounts.2018.exp3.I1.txt 2018/exp3/I1/Aligned.out.bam 
