#!/bin/sh
# gzip 2016/R1/raw.vcf 
# gzip 2016/R2/raw.bcf 
gzip Undetermined_S0_L001_R1_001.fastq > Undetermined_S0_L001-1-R1_001.fastq.gz
gzip Undetermined_S0_L002_R1_001.fastq > Undetermined_S0_L002-2-R1_001.fastq.gz
gzip Undetermined_S0_L001_R2_001.fastq > Undetermined_S0_L001-1-R2_001.fastq.gz
gzip Undetermined_S0_L002_R2_001.fastq > Undetermined_S0_L002-2-R2_001.fastq.gz
