#!/bin/sh
# gzip 2016/R1/raw.vcf 
# gzip 2016/R2/raw.bcf 
#gzip Undetermined_S0_L001_R1_001.fastq
#gzip Undetermined_S0_L002_R1_001.fastq
#gzip Undetermined_S0_L001_R2_001.fastq
gzip Undetermined_S0_L002_R2_001.fastq 
