#!/bin/sh

java -jar gatk-4.0.11.0/gatk-package-4.0.11.0-local.jar \
	-R Danio_rerio.GRCz10.cdna.all.fa \
	-T HaplotypeCaller \
	-I 2016/R1/Aligned.out.sorted.bam \
	-stand_call_conf 20 \
	-o 2016.R1.raw.snps.indels.vcf
