#!/bin/sh

java -jar gatk-4.0.11.0/gatk-package-4.0.11.0-local.jar \
	HaplotypeCaller \
	--reference Danio_rerio.GRCz10.cdna.all.fa \
	--input 2016/R1/Aligned.out.sorted.picard.bam \
	--output 2016.R1.raw.snps.indels.vcf


java -jar gatk-4.0.11.0/gatk-package-4.0.11.0-local.jar \
	HaplotypeCaller \
	--reference Danio_rerio.GRCz10.cdna.all.fa \
	--input 2016/R2/Aligned.out.sorted.picard.bam \
	--output 2016.R2.raw.snps.indels.vcf
