#!/bin/sh
# kallisto index -i transcripts.idx GCA_000002035.4_GRCz11_genomic.fna.gz 
kallisto quant -i transcripts.idx -o output -b 100 Undetermined_S0_L001_R1_001.fastq Undetermined_S0_L001_R2_001.fastq
