#!/bin/sh
#index_gff --index Danio_rerio.GRCz11.95.fixed.gff3 Danio_rerio.GRCz11.95.index


for i in {36..101}
do
  miso --run Danio_rerio.GRCz11.95.index splice/2019_1Aligned.out.sorted.bam --output-dir miso_output_2019_1 --read-len $i
done
for i in {36..101}
do
  miso --run Danio_rerio.GRCz11.95.index splice/2019_7Aligned.out.sorted.bam --output-dir miso_output_2019_7 --read-len $i
done
for i in {36..101}
do
  miso --run Danio_rerio.GRCz11.95.index splice/2019_7controlAligned.out.sorted.bam --output-dir miso_output_2019_7control --read-len $i
done
for i in {36..101}
do
  miso --run Danio_rerio.GRCz11.95.index splice/2019_1controlAligned.out.sorted.bam --output-dir miso_output_2019_1control --read-len $i
done
