#!/bin/sh

#STAR --runThreadN 16 --runMode genomeGenerate --genomeDir ./ --readFilesIn /data/BurgessLab/sequencing/2019_01_cup_mRNAseq/fastq181221_RNAseq/wt_S1_R1_001.fastq.gz /data/BurgessLab/sequencing/2019_01_cup_mRNAseq/fastq181227_RNAseq/WT_S1_R1_001.fastq.gz /data/BurgessLab/sequencing/2019_01_cup_mRNAseq/fastq181221_RNAseq/mut_S2_R1_001.fastq.gz /data/BurgessLab/sequencing/2019_01_cup_mRNAseq/fastq181227_RNAseq/Mut_S2_R1_001.fastq.gz --sjdbGTFfile Danio_rerio.GRCz11.94.gtf.gz --sjdbOverhang 50 --outFilterType BySJout --genomeChrBinNbits 6 --readFilesCommand zcat

STAR --runThreadN 16 --runMode alignReads --outSAMtype BAM Unsorted --genomeDir ./ --readFilesIn /data/BurgessLab/sequencing/2019_01_cup_mRNAseq/fastq181221_RNAseq/mut_S2_R1_001.fastq.gz --sjdbOverhang 100 --readFilesCommand zcat --outFileNamePrefix /data/athersh/2019_1
STAR --runThreadN 16 --runMode alignReads --outSAMtype BAM Unsorted --genomeDir ./ --readFilesIn /data/BurgessLab/sequencing/2019_01_cup_mRNAseq/fastq181227_RNAseq/Mut_S2_R1_001.fastq.gz --sjdbOverhang 100 --readFilesCommand zcat --outFileNamePrefix /data/athersh/2019_7 

STAR --runThreadN 16 --runMode alignReads --outSAMtype BAM Unsorted --genomeDir ./ --readFilesIn /data/BurgessLab/sequencing/2019_01_cup_mRNAseq/fastq181221_RNAseq/wt_S1_R1_001.fastq.gz --sjdbOverhang 100 --readFilesCommand zcat --outFileNamePrefix /data/athersh/2019_1control
STAR --runThreadN 16 --runMode alignReads --outSAMtype BAM Unsorted --genomeDir ./ --readFilesIn /data/BurgessLab/sequencing/2019_01_cup_mRNAseq/fastq181227_RNAseq/WT_S1_R1_001.fastq.gz --sjdbOverhang 100 --readFilesCommand zcat --outFileNamePrefix /data/athersh/2019_7control
